# Generated by Django 4.2.16 on 2026-07-24 04:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('secure', models.BooleanField(default=False)),
                ('http_only', models.BooleanField(default=False)),
                ('same_site', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('interesting', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=16)),
                ('confidence', models.CharField(default='Firm', max_length=32)),
                ('affected_url', models.URLField(blank=True, max_length=2048)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('evidence', models.TextField(blank=True)),
                ('proof', models.TextField(blank=True)),
                ('payload', models.TextField(blank=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cwe', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('detected_by', models.CharField(blank=True, max_length=120)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['scan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=2048)),
                ('action', models.URLField(blank=True, max_length=2048)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('form_kind', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['page_url'],
            },
        ),
        migrations.CreateModel(
            name='HttpHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.TextField(blank=True)),
                ('is_security_header', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('error', 'error'), ('cmd', 'cmd')], default='info', max_length=10)),
                ('phase', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=8)),
                ('state', models.CharField(default='open', max_length=16)),
                ('service', models.CharField(blank=True, max_length=64)),
                ('product', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2048)),
                ('hostname', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('phase', models.CharField(blank=True, default='Queued', max_length=120)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_task', models.CharField(blank=True, max_length=255)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_urls_discovered', models.PositiveIntegerField(default=0)),
                ('security_score', models.PositiveSmallIntegerField(default=100)),
                ('risk_rating', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('minimal', 'Minimal')], default='minimal', max_length=16)),
                ('executive_summary', models.TextField(blank=True)),
                ('recon', models.JSONField(blank=True, default=dict)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='scanner.scan')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status'], name='scanner_sca_status_bc0197_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['created_at'], name='scanner_sca_created_6012ae_idx'),
        ),
        migrations.AddField(
            model_name='port',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scanner.scan'),
        ),
        migrations.AddField(
            model_name='logline',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.scan'),
        ),
        migrations.AddField(
            model_name='httpheader',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='scanner.scan'),
        ),
        migrations.AddField(
            model_name='form',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='scanner.scan'),
        ),
        migrations.AddField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scanner.scan'),
        ),
        migrations.AddField(
            model_name='cookie',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='scanner.scan'),
        ),
        migrations.AlterUniqueTogether(
            name='technology',
            unique_together={('scan', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('scan', 'number', 'protocol')},
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan', 'severity'], name='scanner_fin_scan_id_ac2d4f_idx'),
        ),
    ]
